apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ckad-db
  namespace: db001
spec:
  selector:
    matchLabels:
      app: db
  serviceName: ckad-db
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: ckad-db
          image: postgres
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: POSTGRES_USER
              value: nigel
            - name: POSTGRES_PASSWORD
              value: k8srocks
            - name: POSTGRES_DB
              value: store  
#          livenessProbe:
#            exec:
#              command:
#                - sh
#                - -c
#                - exec pg_isready --host $POD_IP
#            failureThreshold: 6
#            initialDelaySeconds: 60
#            periodSeconds: 10
#            successThreshold: 1
#            timeoutSeconds: 5
#          readinessProbe:
#            exec:
#              command:
#                - sh
#                - -c
#                - exec pg_isready --host $POD_IP
#            failureThreshold: 3
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            successThreshold: 1
#            timeoutSeconds: 3
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/pgdata
              name: postgres
              subPath: postgres-db
  volumeClaimTemplates:
  - metadata:
      name: postgres
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: linode-block-storage
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ckad-db
  namespace: db001
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: db
