apiVersion: v1
kind: Pod
metadata:
  name: svc-app
  namespace: exam-ckad
  labels:
    project: exam-cram
spec:
  containers:
  - name: app
    image: nigelpoulton/web-app:1.0
    ports:
      - containerPort: 8080
