apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-web
  namespace: ckad003
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-fe
      project: ps-ckad
  template:
    metadata:
      labels:
        app: web-fe
        project: ps-ckad
    spec: 
      containers:
      - name: ctr
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        ports:
        - containerPort: 8080
        image: nigelpoulton/qsk-book:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: ckad003
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: web-fe
    project: ps-ckad
