apiVersion: batch/v1
kind: CronJob
metadata:
  name: sleeper
  namespace: exam-ckad
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ctr
            image: alpine:latest
            imagePullPolicy: Always
            command: ["sleep",  "10"]
          restartPolicy: OnFailure