apiVersion: v1
kind: Pod
metadata:
  name: web500
  namespace: ckad002
  labels:
    project: qsk-book
spec:
  containers:
  - name: qsk-pod
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
    image: nigelpoulton/qsk-book:1.0
